version: '3.7'

services:
  main:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./prisma:/usr/src/app/prisma
      - ./schema.prisma:/usr/src/app/schema.prisma
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb
      - minio

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - webnet
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongodata:/data/db

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    volumes:
      - .:/data
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - webnet

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
volumes:
  mongodata:
  minio_storage:
