import process from 'process'

export const USER_NOT_FOUND = 'User not found'
export const DUPLICATED_EMAIL = 'Email is already in use'
export const INVALID_PASSWORD_LENGTH = 'Password must be at least 8 characters long'
export const INVALID_PASSWORD_FORMAT =
  'Password must contain at least 1 letter, 1 number, and 1 special character'
export const INCORRECT_CREDENTIAL = 'Incorrect login credentials'
export const OTP_EMAIL_SEND_FAILED = 'Failed to send OTP email'
export const OTP_EMAIL_SEND_SUCCESS = 'OTP email sent successfully'
export const EMAIL_ADMIN = 'nguyenhoangnam31082000@gmail.com'
export const SUPER_ADMIN = 'SUPER_ADMIN'
export const DEFAULT_ROLE = 'STUDENT'
export const PROD_ENV = 'production'
export const DEV_ENV = 'development'
export const MESSAGE_REQUIRED = 'This field is required'
